### ISSUE TITLE
Opret login dialog

### ISSUE THREAD

**Issue by jedelbo** [aelillie/Shopping-list#1]
Der skal oprettes en login dialog, hvor man kan indtaste bruger og password

**Comment by aelillie** [comment]
Skal der accepteres hvilke som helst brugernavne og password, eller hvordan skal dette valideres?

**Comment by jedelbo** [comment]
Der behøves ingen validering i første omgang. Man kan lade sig inspirere af, hvordan det er gjort i `objectServerExample` i realm-java projektet
